name: Release

on:
  push:
    branches:
      - main

jobs:
  require-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: sadik-malik
          minimum-approvals: 1
          issue-title: "Manual approval required to release"
          issue-body: "Please approve to continue with the release."
          exclude-workflow-initiator-as-approver: false

  release:
    needs: require-approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Release (non-interactive)
        env:
          NODE_ENV: production
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release -y
